### ISSUE TITLE
error reading the quote and facts script.

### ISSUE THREAD

**Issue by agpenton** [akpakshendra/Serene-Conky#7]
i have some problem with the quotes and the facts....when i run the script...i get this error
```
Traceback (most recent call last):
  File "Scripts/quote.py", line 48, in <module>
    data = readQuote(config)
  File "Scripts/quote.py", line 29, in readQuote
    data[str(i+1) + 'quote'] = unicode(quotes[i].a.text).strip()
IndexError: list index out of range
sh: 1: /sbin/route: not found
conky: llua_do_call: function conky_main execution failed: ./Core/fact.lua:12: attempt to index global 'key' (a nil value)
```
Another problem is that the icons don't show...

**Comment by FrdVnW** [comment]
I made the correction and made a pull request. Quote is OK now (on my computer ;-))
